# Generated by Django 5.1.4 on 2024-12-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=64)),
                ('description', models.TextField(default='Description', max_length=6000)),
                ('writer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.writer')),
            ],
        ),
    ]
